### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by orchoban** [DataCyberDevelopment/Biznalitics_HTML#16]
We need template to start build with it.

I started to create one.
https://github.com/DataCyberDevelopment/Biznalitics_HTML/blob/main/build/template.html

same problems to fix:
 
- [x] 1. Remove link tag `crm.css`
- [x] 2. pattern need 100% height.
- [x] 3. Center logo.
 
1. Remove [link tag `crm.css`](https://github.com/DataCyberDevelopment/Biznalitics_HTML/blob/0f4630062dc4f0b181899eb665e0de454fb4452b/build/template.html#L19). 
I tried to do it but it's left same styles

2. pattern need 100% height.
![image](https://user-images.githubusercontent.com/33927385/129182684-32314153-6be2-4440-bf45-53c2435fbf08.png)

3. logo need center.
![image](https://user-images.githubusercontent.com/33927385/129183109-fb551007-02f7-4c52-a221-a767b564bf9d.png)

**Comment by w3codemaster** [comment]
@orchoban done
