### ISSUE TITLE
Style changes on Client-Card Page

### ISSUE THREAD

**Issue by banaagravrommel** [DataCyberDevelopment/Biznalitics_HTML#25]
![client-card-1](https://user-images.githubusercontent.com/51908980/129291633-cde72a86-c932-4286-8e35-a0343b72f87c.png)
![client-card-2](https://user-images.githubusercontent.com/51908980/129291639-ef4dbd1a-f649-4ecb-a48e-0d483b55b2b0.png)

- [x] 1. Should have smaller space before the next section
- [x] 2. Field width should be smaller
- [x] 3. Field width should be smaller
- [x] 4. Field width should be bigger
- [x] 5. Field height should be bigger
- [x] 6. Field height should be bigger
- [x] 7. Tabs width should be bigger

**Comment by w3codemaster** [comment]
@orchoban  solved #client-card
