### ISSUE TITLE
Style Changes on Client-Card-List Page

### ISSUE THREAD

**Issue by banaagravrommel** [DataCyberDevelopment/Biznalitics_HTML#26]
![client-card-list](https://user-images.githubusercontent.com/51908980/129291767-751aff8c-67ab-4bf7-9780-46c8c620d996.png)

- [x] 1. Changes from this section is listed from Client-Card
- [x] 2. Fields should be closer
- [x] 3. Number field with the gray section should be closer to the image
- [x] 4. Row cards should have smaller grap
- [x] 5. Button should be wider

**Comment by w3codemaster** [comment]
@orchoban  solved    #client-card-list
