### ISSUE TITLE
Style Changes on Client-Card-Mailbox Page

### ISSUE THREAD

**Issue by banaagravrommel** [DataCyberDevelopment/Biznalitics_HTML#30]
![client-card-mailbox](https://user-images.githubusercontent.com/51908980/129292925-d263dd82-c8fa-45bc-b4a6-6da8b48cfdde.png)

- [x] 1. Tabs should have bigger gap
- [x] 2. Whole gray section should be moved further to the right. Close to the tabs
- [x] 3. Time icon should be smaller

**Comment by w3codemaster** [comment]
@orchoban  solved
