### ISSUE TITLE
Style Changes on Client-List

### ISSUE THREAD

**Issue by banaagravrommel** [DataCyberDevelopment/Biznalitics_HTML#31]
![client-list](https://user-images.githubusercontent.com/51908980/129293074-b18fbed7-78ec-492a-96f7-db0ba5215231.png)
![client-list-1](https://user-images.githubusercontent.com/51908980/129293165-176e194f-c959-49df-b5f7-32bf0363250e.png)
![client-list-2](https://user-images.githubusercontent.com/51908980/129293170-bc9a25a2-4829-4d09-b674-299c4ae2dbfc.png)

- [x] 1. Vertical bar missing
- [x] 2. Icon should be bigger and more on the right
- [x] 3. The Check/Cross icon should be a bit bigger and more on the top. Blue number text should be on the far right.
- [x] 4. Component should be more compact
- [x] 5. Arrow icon style is different
- [x] 6. Every data on the row should be closer to the vertical bar.
- [x] 7. Pencil icon and File icon should be on the far right.

**Comment by w3codemaster** [comment]
@orchoban  solved
