### ISSUE TITLE
Style Changes on Add-Client

### ISSUE THREAD

**Issue by banaagravrommel** [DataCyberDevelopment/Biznalitics_HTML#32]
![add-client](https://user-images.githubusercontent.com/51908980/129293453-36f7775e-2ef2-44e6-b61f-ebe7835ac6cb.png)

- [x] 1. Missing asterisk (*) icon
- [x] 2. Missing asterisk (*) icon and dropdown should not exist
- [x] 3. Extra gray section should be remove
- [x] 4. Missing asterisk (*) icon
- [x] 5. Missing asterisk (*) icon
- [x] 6. Profile icon should be bigger
- [x] 7. Buttons should be more on the top aligned with the text in the far right.

**Comment by w3codemaster** [comment]
@orchoban  solved
