### ISSUE TITLE
Style Changes on Upload-File

### ISSUE THREAD

**Issue by banaagravrommel** [DataCyberDevelopment/Biznalitics_HTML#33]
![upload-file](https://user-images.githubusercontent.com/51908980/129293549-fc7cb905-9ccd-4bd7-bc05-5954afbb96e0.png)

- [x] 1. Icon is different
- [x] 2. Icon is different
- [x] 3. Text should be on the further right
- [x] 4. Missing underline on the blue text
- [x] 5. Icon is different

**Comment by w3codemaster** [comment]
@orchoban   solved
