### ISSUE TITLE
Responsiveness on different pages

### ISSUE THREAD

**Issue by banaagravrommel** [DataCyberDevelopment/Biznalitics_HTML#37]
**General error where the following happens to most pages with the same structure.**
Desktop

- [x] 1. Issue with desktop where there is a certain resolution scrolling is not allowed leading users to not see the bottom part. **(1920x1080 , Zoom 110% and 100%)**
[Screen Record](https://www.awesomescreenshot.com/video/4823449?key=94603bc28c8758f0d089284fe04892bf)
Mobile

- [x] 1. Blue line too close to the scrollbar.

![r-1](https://user-images.githubusercontent.com/51908980/129294623-0c241219-9624-49ee-aa6f-246eff8d03a9.PNG)

- [x] 2. Some details on the header are missing like the location and building field.
![r-4](https://user-images.githubusercontent.com/51908980/129295254-8f64c971-af60-44b3-b336-7500100664d5.PNG)

Client-Card

- [x] Tablet - Issue on Ipad Pro resolution where there are excess white space

![r-2](https://user-images.githubusercontent.com/51908980/129294876-cd675c23-b6e1-4d99-b1ae-59280c53281e.PNG)

Client-Card-Mailbox

- [ ] Desktop - Mailbox icon gets smaller as the resolution gets smaller.
[Screen Record](https://www.awesomescreenshot.com/video/4823573?key=226d906aab06db8a8f6471a16c374c3b)

Client-List

- [ ] Desktop - There is one issue where a certain resolution moves the far left calendar field to the bottom of the right. **(1920x1080 then 125% zoom on Chrome)**
![r-3](https://user-images.githubusercontent.com/51908980/129295155-a46f0820-0bd8-4ab1-bb5e-b285a3d2ddb3.PNG)

**Comment by w3codemaster** [comment]
@orchoban  solved

and dont use zoom in and zoom out   check pages on   common screen sizes like:- 


1920 x  1080
1400 x  900
1366 x  768
1280 x  720
1024 x  768
768  x  1024
360  x  640

**Comment by w3codemaster** [comment]
@orchoban  solved
