### ISSUE TITLE
Link2 -modal bottom 

### ISSUE THREAD

**Issue by orchoban** [DataCyberDevelopment/Biznalitics_HTML#6]
we can see item below the bottom of the modal
![image](https://user-images.githubusercontent.com/33927385/128725215-a54b1c70-8420-44ec-b2ff-08545e1a274e.png)
![image](https://user-images.githubusercontent.com/33927385/128725349-89bbe1a1-ba81-4f3a-b945-a432be53b82e.png)

Figma:
![image](https://user-images.githubusercontent.com/33927385/128726103-268f4867-a64c-477c-a0b4-2b4c99b10781.png)

**Comment by w3codemaster** [comment]
@orchoban  solved

**Comment by orchoban** [comment]
![Uploading image.png…]()

**Comment by orchoban** [comment]
@w3codemaster.
Still same.
If you fix it you have to tag here commit for this.
  ![image](https://user-images.githubusercontent.com/33927385/129162707-68941f25-0505-4ddb-b6a9-137472ebc61d.png)

**Comment by w3codemaster** [comment]
@orchoban  i solved i will give you  updated files
